### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by jriede** [TeXhackse/CCCamp19_beamer#1]
Compilation succeeds with lots of errors, both fonts have been installed as system fonts. Thanks for having a look!

[log.txt](https://github.com/TeXhackse/CCCamp19_beamer/files/3480517/log.txt)

**Comment by TeXhackse** [comment]
You should update your TeX Distribution, its 2016 texlive ;-)

I think the rest of the problems will then be solved.

**Comment by jriede** [comment]
Knew the problem was on my side. Will do, thanks!

**Comment by TeXhackse** [comment]
If it works, just close the issue, I added a note to the readme. Otherwise I need a new log ;-)

**Comment by jriede** [comment]
TeX distro updated (LuaTeX, Version 1.10.0 (TeX Live 2019)), still issues (see attached files). Thanks for your help!

[log.txt](https://github.com/TeXhackse/CCCamp19_beamer/files/3481543/log.txt)
[DEMO-cccamp19-beamer.pdf](https://github.com/TeXhackse/CCCamp19_beamer/files/3481547/DEMO-cccamp19-beamer.pdf)

**Comment by perreira** [comment]
I needed to install FiraCode as OTF manually, the Fira packages from TeX live did not work. Then run '''luaotfload-tool --update''' to update the Font DB. It then compiled with juts a ton of warnings from hyperref which I ignored :-)

**Comment by perreira** [comment]
https://github.com/tonsky/FiraCode

**Comment by TeXhackse** [comment]
for her the problem was different, we solved it by updating. Just forgot to close the issue.
